version: "3.8"

services:
  app:
    image: "cynax/php:7.4-fpm"
    container_name: XiT_assessment
    depends_on:
      - db
    links:
      - "db"
    volumes:
      - .:/var/www/html
    command: bash -c 'php -S 0.0.0.0:8000'
    ports:
      - "80:8000"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main_db
      MYSQL_USER: cynax
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"